// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/core-concepts": {
    params: {};
  };
  "/docs/features": {
    params: {};
  };
  "/docs/helpers": {
    params: {};
  };
  "/docs/config": {
    params: {};
  };
  "/docs/components": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs" | "/docs/core-concepts" | "/docs/features" | "/docs/helpers" | "/docs/config" | "/docs/components";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/docs.core-concepts.tsx": {
    id: "routes/docs.core-concepts";
    page: "/docs/core-concepts";
  };
  "routes/docs.features.tsx": {
    id: "routes/docs.features";
    page: "/docs/features";
  };
  "routes/docs.helpers.tsx": {
    id: "routes/docs.helpers";
    page: "/docs/helpers";
  };
  "routes/docs.config.tsx": {
    id: "routes/docs.config";
    page: "/docs/config";
  };
  "routes/docs.components.tsx": {
    id: "routes/docs.components";
    page: "/docs/components";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/docs.core-concepts": typeof import("./app/routes/docs.core-concepts.tsx");
  "routes/docs.features": typeof import("./app/routes/docs.features.tsx");
  "routes/docs.helpers": typeof import("./app/routes/docs.helpers.tsx");
  "routes/docs.config": typeof import("./app/routes/docs.config.tsx");
  "routes/docs.components": typeof import("./app/routes/docs.components.tsx");
};